"""add_composite_workflow_fields

Revision ID: 01c0a7e9cf59
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 14:25:52.797989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c0a7e9cf59'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_composite', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('workflows', sa.Column('composite_steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'composite_steps')
    op.drop_column('workflows', 'is_composite')
    # ### end Alembic commands ###
