"""add playback_position to media

Revision ID: 299dd384a3fb
Revises: bbe4681a2d80
Create Date: 2026-03-12 18:18:25.296111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299dd384a3fb'
down_revision: Union[str, None] = 'bbe4681a2d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('playback_position', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'playback_position')
    # ### end Alembic commands ###
