"""add video_timestamp and parent_media_id index

Revision ID: 4f48ad5b1d69
Revises: de196ed5208f
Create Date: 2026-03-05 11:32:16.930233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f48ad5b1d69'
down_revision: Union[str, None] = 'de196ed5208f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('video_timestamp', sa.Float(), nullable=True))
    op.create_index('ix_media_parent', 'media', ['parent_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_parent', table_name='media')
    op.drop_column('media', 'video_timestamp')
    # ### end Alembic commands ###
