"""remove_upscale_status_column

Revision ID: 692ed7cdc91c
Revises: 97db555688f3
Create Date: 2026-03-03 23:12:07.203883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692ed7cdc91c'
down_revision: Union[str, None] = '97db555688f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'upscale_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('upscale_status', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
