"""add batch_id to tasks

Revision ID: 8efa839191e2
Revises: 65623ed0957a
Create Date: 2026-03-16 20:30:24.840489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efa839191e2'
down_revision: Union[str, None] = '65623ed0957a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('batch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tasks_batch_id'), 'tasks', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_batch_id'), table_name='tasks')
    op.drop_column('tasks', 'batch_id')
    # ### end Alembic commands ###
