"""init_v2

Revision ID: 97db555688f3
Revises: 
Create Date: 2026-03-02 18:58:15.362836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97db555688f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('rated_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_mode', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_order', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('result_media_ids', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('is_generated_album', sa.Boolean(), nullable=False),
    sa.Column('source_face_media_id', sa.String(length=36), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('rated_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_person_id'), 'albums', ['person_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('album_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('parent_media_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_type', sa.String(length=50), nullable=True),
    sa.Column('generation_params', sa.String(length=5000), nullable=True),
    sa.Column('upscale_status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=2000), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_album_id'), 'media', ['album_id'], unique=False)
    op.create_index('ix_media_album_sort', 'media', ['album_id', 'sort_order'], unique=False)
    op.create_index('ix_media_deleted_at', 'media', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_media_is_deleted'), 'media', ['is_deleted'], unique=False)
    op.create_index('ix_media_person_deleted', 'media', ['person_id', 'is_deleted'], unique=False)
    op.create_index('ix_media_rating', 'media', ['rating'], unique=False)
    op.create_table('workspace_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_items')
    op.drop_index('ix_media_rating', table_name='media')
    op.drop_index('ix_media_person_deleted', table_name='media')
    op.drop_index(op.f('ix_media_is_deleted'), table_name='media')
    op.drop_index('ix_media_deleted_at', table_name='media')
    op.drop_index('ix_media_album_sort', table_name='media')
    op.drop_index(op.f('ix_media_album_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_albums_person_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_table('tasks')
    op.drop_table('queue_config')
    op.drop_table('persons')
    # ### end Alembic commands ###
