"""add platform_account and download_record

Revision ID: de196ed5208f
Revises: 692ed7cdc91c
Create Date: 2026-03-05 10:27:05.758591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de196ed5208f'
down_revision: Union[str, None] = '692ed7cdc91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_person_id'), 'platform_accounts', ['person_id'], unique=False)
    op.create_index(op.f('ix_platform_accounts_platform'), 'platform_accounts', ['platform'], unique=False)
    op.create_table('download_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(length=36), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_records_platform'), 'download_records', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_records_platform'), table_name='download_records')
    op.drop_table('download_records')
    op.drop_index(op.f('ix_platform_accounts_platform'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_person_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    # ### end Alembic commands ###
